using PerfReg.Analysis;
using PerfReg.Models;
using System.Text;

namespace PerfReg.Reporting;

public class GitHubActionsReporter : IReporter
{
    private readonly MarkdownReporter _markdownReporter;

    public GitHubActionsReporter()
    {
        _markdownReporter = new MarkdownReporter();
    }

    public void ShowResult(BenchmarkResult result)
    {
        // Output as GitHub Actions annotations
        if (result.Statistics != null)
        {
            var stats = result.Statistics;
            Console.WriteLine($"::notice title=Benchmark Results::Runtime: {result.RuntimeMs:F2}ms (±{stats.Runtime.StdDev:F2}ms), Memory: {result.PeakMemoryBytes / 1024.0 / 1024.0:F2}MB (±{stats.Memory.StdDev / 1024.0 / 1024.0:F2}MB)");
        }
        else
        {
            Console.WriteLine($"::notice title=Benchmark Results::Runtime: {result.RuntimeMs:F2}ms, Memory: {result.PeakMemoryBytes / 1024.0 / 1024.0:F2}MB");
        }

        Console.WriteLine();
        Console.WriteLine("<!-- BENCHMARK_RESULTS -->");
        _markdownReporter.ShowResult(result);
        Console.WriteLine("<!-- /BENCHMARK_RESULTS -->");
    }

    public void ShowComparison(ComparisonReport report)
    {
        // Output warnings for regressions
        foreach (var metric in report.Metrics.Where(m => m.IsRegression))
        {
            Console.WriteLine($"::warning title=Performance Regression::{metric.Name} regressed by {metric.PercentageChange:F1}% ({metric.PreviousValue:F2}{metric.Unit} → {metric.CurrentValue:F2}{metric.Unit})");
        }

        Console.WriteLine();
        Console.WriteLine("<!-- BENCHMARK_COMPARISON -->");
        _markdownReporter.ShowComparison(report);
        Console.WriteLine("<!-- /BENCHMARK_COMPARISON -->");
    }

    public void ShowHistory(BenchmarkHistory history)
    {
        _markdownReporter.ShowHistory(history);
    }

    public static string GeneratePRComment(ComparisonReport comparison, BenchmarkResult result)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# 📊 Performance Benchmark Results");
        sb.AppendLine();

        bool hasRegressions = comparison.Metrics.Any(m => m.IsRegression);

        if (hasRegressions)
        {
            sb.AppendLine("> ⚠️ **Performance regressions detected**");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("> ✅ **No performance regressions detected**");
            sb.AppendLine();
        }

        sb.AppendLine("## Comparison");
        sb.AppendLine();
        sb.AppendLine($"**Current:** `{comparison.Current.CommitHash}` ({comparison.Current.Timestamp:yyyy-MM-dd HH:mm:ss})");
        sb.AppendLine($"**Previous:** `{comparison.Previous.CommitHash}` ({comparison.Previous.Timestamp:yyyy-MM-dd HH:mm:ss})");
        sb.AppendLine();

        sb.AppendLine("| Metric | Current | Previous | Change | Status |");
        sb.AppendLine("|--------|---------|----------|--------|--------|");

        foreach (var metric in comparison.Metrics)
        {
            var changeStr = $"{(metric.PercentageChange >= 0 ? "+" : "")}{metric.PercentageChange:F1}%";
            var status = metric.Direction switch
            {
                ChangeDirection.Degraded when metric.IsRegression => "⚠️ Regression",
                ChangeDirection.Degraded => "↑ Slower",
                ChangeDirection.Improved => "✓ Improved",
                _ => "→ Unchanged"
            };

            sb.AppendLine($"| {metric.Name} | {metric.CurrentValue:F2}{metric.Unit} | {metric.PreviousValue:F2}{metric.Unit} | {changeStr} | {status} |");
        }

        if (result.Statistics != null)
        {
            var stats = result.Statistics;
            sb.AppendLine();
            sb.AppendLine("## Statistics");
            sb.AppendLine();
            sb.AppendLine($"**Configuration:** {stats.TotalRuns} run(s), {stats.WarmupRuns} warmup(s)");
            sb.AppendLine();
            sb.AppendLine("| Metric | Mean | StdDev | Min | Median | Max |");
            sb.AppendLine("|--------|------|--------|-----|--------|-----|");
            sb.AppendLine($"| Runtime | {result.RuntimeMs:F2}ms | ±{stats.Runtime.StdDev:F2}ms | {stats.Runtime.Min:F2}ms | {stats.Runtime.Median:F2}ms | {stats.Runtime.Max:F2}ms |");
            sb.AppendLine($"| Memory | {result.PeakMemoryBytes / 1024.0 / 1024.0:F2}MB | ±{stats.Memory.StdDev / 1024.0 / 1024.0:F2}MB | {stats.Memory.Min / 1024.0 / 1024.0:F2}MB | {stats.Memory.Median / 1024.0 / 1024.0:F2}MB | {stats.Memory.Max / 1024.0 / 1024.0:F2}MB |");
        }

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*Generated by [PerfReg](https://github.com/anthropics/perfreg)*");

        return sb.ToString();
    }
}
